# This job checks incomming changes by building example code and
# running unit tests
name: test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - '.vscode/**'

permissions:
  contents: read

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        zig: [0.15.1] 
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          # Workaround #271
          - os: ubuntu-latest
            build_flags: -Doptimize=ReleaseFast
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig }}

      - name: Check Formatting
        if: runner.os != 'Windows' # zig fmt failing on Windows CI due to CLRF vs LF, skip
        run: zig fmt --ast-check --check .

      - name: Build examples
        run: zig build -Denable_ztracy=false ${{ matrix.build_flags }}

      - name: Build examples with ztracy
        run: zig build -Denable_ztracy=true ${{ matrix.build_flags }}

      - name: Build documentation
        run: zig build doc

      - name: Run tests
        run: zig build test ${{ matrix.build_flags }}

      - name: Run readme
        run: zig build run-readme ${{ matrix.build_flags }}
  

